### ISSUE TITLE
Disable automatic notification prompt on Android 13+

### ISSUE THREAD

**Issue by baudouxbenjamin** [wonderpush/wonderpush-android-sdk#11]
Hi,

Is there any way to disable the automatic notification prompt on Android 13+ when using `WonderPush.subscribeToNotifications()` ?

I'd like to handle the prompt myself...

Thanks

**Comment by ofavre** [comment]
Hi,

In order to control when the prompt is show, your application first needs to use `targetSdkVersion 33` or ulterior.

Then you need to call either of the below options at the desired time:

```
// Shows the push permission prompt when necessary
WonderPush.subscribeToNotifications();

// You can also use this variation that will show an alert dialog
// to users who have repeatedly denied the permission, taking them to the settings
// of your app where they can flip the permission switch:
WonderPush.subscribeToNotifications(true);
```

You can explain to the user during onboarding what value they will receive by accepting push notifications before calling the above.
Also if you have a button or a switch in your UI to follow some topic, the click handler is a good place to call it, especially the second variant.

**Comment by baudouxbenjamin** [comment]
So the answer to my original question 

_Is there any way to disable the automatic notification prompt on Android 13+ when using `WonderPush.subscribeToNotifications()` ?_ 

is **no**. 

I don't want an external SDK to be responsible of displaying UI to my user. `WonderPush.subscribeToNotifications()` should just do what the function name says: subscribe to notifications and nothing else.
